### ISSUE TITLE
export path libIccXML2.so.2 

### ISSUE THREAD

**Issue by 24fpsDaVinci** [InternationalColorConsortium/DemoIccMAX#63]
for me the correct export path was `export LD_LIBRARY_PATH=$HOME/.local/lib64:$LD_LIBRARY_PATH`
this is for the debug build flag in the instructions example

**Comment by xsscx** [comment]
Hello @24fpsDaVinci 

Thank you for sharing your confirmed working export example, very helpful.

The existing instructions are: https://github.com/InternationalColorConsortium/DemoIccMAX/blob/55f4f773498a294d35fe5d26a6fd5909dda8d57f/Readme.md?plain=1#L343

A rough draft for your PR for the updated instructions may take the form of:
...
### Linux Issues and Solutions

You may also need to set `LD_LIBRARY_PATH` to `CMAKE_INSTALLPREFIX`/lib so that
`libIccProfLib2.so` and `libIccXML.so` shared libraries can be located at runtime.

Depending on the Host:
```bash
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
```
or
```bash
export LD_LIBRARY_PATH=$HOME/.local/lib64:$LD_LIBRARY_PATH
```
...
Submit a PR if you can, or I can add into my next PR.

Thank you for the confirmed datapoint, very helpful for all to reference.

**Comment by xsscx** [comment]
PR Merged in https://github.com/InternationalColorConsortium/DemoIccMAX/pull/83
